"""
Django settings for TCSDB project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w!xmoe0)0jd=y&wqt%ax76u)mlce8^f$7ku$w%&f7kpvu6!+&c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'monitor.apps.MonitorConfig',
    'testcase.apps.TestcaseConfig',
    'rbac.apps.RbacConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middlewares.rbac.RbacMiddleware',  # 鏉冮檺涓棿浠�
]

ROOT_URLCONF = 'TCSDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TCSDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME'  : 'testcases',
        'USER'  : 'cuimei',
        'PASSWORD': '123456',
        'HOST'   : '127.0.0.1',
        'PORT'   : '5432',
#     'ENGINE': 'django.db.backends.mysql',
#     'NAME':'tcsdb',
#     'USER': 'root',
#     'PASSWORD': '',
#     'HOST': 'localhost',
#     'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# STATIC_ROOT = os.path.join(BASE_DIR,'static')

API_TOKEN = "7d6766a6s5f76safas657889hj78kf91"
############################ 鏉冮檺绠＄悊鐩稿叧 ################################
PERMISSION_MENU_KEY = "w*d6v&ns8qq_y#1f"
# 涓嶇敤鐧婚檰鍙闂〉闈�
VALID_URL= [
    '^/login/',
    # '^/api/auth/',
    '^/get_code/',
    # '^/index/',
    # '^/index_v3/',
    '^/403/',
    '^/logout/',
    '^/monitor/api/',
    '^/testcase/api/',
]

APPEND_SLASH=False
###############################其它设置##################################
SERVER_IP = ''
CODE_FONT_FILE = os.path.join(BASE_DIR,'static/fonts/wqy-microhei.ttc')  #璁剧疆楠岃瘉鐮佸瓧浣撴枃浠�

##################### 鍒嗛〉鍣ㄨ缃� ########################################

PER_PAGE = 20    #姣忛〉鏄剧ず鏁版嵁鏁�
PAGER_PAGE_COUNT = 11    #椤甸潰涓婃渶澶氭樉绀洪〉鐮佹暟

##################### session閰嶇疆 ######################################
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 寮曟搸锛堥粯璁わ級
SESSION_COOKIE_NAME = "sessionid"  # Session鐨刢ookie淇濆瓨鍦ㄦ祻瑙堝櫒涓婃椂鐨刱ey锛屽嵆锛歴essionid=闅忔満瀛楃涓诧紙榛樿锛�
SESSION_COOKIE_PATH = "/"  # Session鐨刢ookie淇濆瓨鐨勮矾寰勶紙榛樿锛�
SESSION_COOKIE_DOMAIN = None  # Session鐨刢ookie淇濆瓨鐨勫煙鍚嶏紙榛樿锛�
SESSION_COOKIE_SECURE = False  # 鏄惁Https浼犺緭cookie锛堥粯璁わ級
SESSION_COOKIE_HTTPONLY = True  # 鏄惁Session鐨刢ookie鍙敮鎸乭ttp浼犺緭锛堥粯璁わ級
# SESSION_COOKIE_AGE = 3600  # Session鐨刢ookie澶辨晥鏃ユ湡锛�1灏忔椂锛夛紙榛樿1209600 2鍛級
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 鏄惁鍏抽棴娴忚鍣ㄤ娇寰桽ession杩囨湡锛堥粯璁alse锛�
SESSION_SAVE_EVERY_REQUEST = True  # 鏄惁姣忔璇锋眰閮戒繚瀛楽ession锛岄粯璁や慨鏀逛箣鍚庢墠淇濆瓨锛堥粯璁alse锛�

########################### 鏃ュ織鏂囦欢閰嶇疆 ########################################
LOG_FILE_PATH = os.path.join(BASE_DIR,'log')
LOG_BACKUP_COUNT = 5
LOG_MAX_BYTES = 1024*1024*5


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}